name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker build 
    - uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
    - uses: docker/login-action@v1
      with: |
       registry: ghcr.io      
       docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_SECRET}}
    - name: Build and push
    - uses: docker/build-push-action@v2
      with: 
        push: true
        tags: ranjithreddy321 /test
