name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
    - name: add ref
      if: ${{ github.ref == 'refs/heads/regular1' }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        tags: ranjithreddy321/test
